Add transparency feature
jtheoof/swappy pull request #164
Opened 2024-02-24 18:20 UTC by kadamski

It is sometimes better if the drawing is not fully covering the picture but is semi-transparent. This patch adds a simple button to enable transparency. When this button is enabled, everything will be drawn with 50% alpha channel.

2024-06-04 13:41 UTC, Shadorain commented
Why is this PR not merged?

2024-10-26 00:28 UTC, jtheoof commented
I would prefer a more complete approach. If we enable transparency it would have its own slider from 0 to 100. Maybe 50% for you would not mean transparent for other users.

2024-10-26 00:30 UTC, jtheoof requested changes

2024-10-26 00:30 UTC, jtheoof commented on src/application.c
> +  if (state->config->transparent) state->settings.a *= 0.5;
This is just too much "magic number". Transparency, once enabled, should be configurable by the user.

2025-08-19 00:28 UTC, jtheoof commented
Thank you for this @kadamski it's pretty good. The only thing is that you forgot to update the README with the new config and tooling support (very close to what you did with the .scd file).

2025-08-19 00:42 UTC, jtheoof requested changes
Nice work. Almost there. The only thing is that you forgot to update the README with the new config and tooling support (very close to what you did with the .scd file).

2025-08-19 20:10 UTC, kadamski commented
@jtheoof thank you for reviewing that. I force-pushed the rebased commits to my branch and added a small one on top that syncs the info in man page to the README file. If there's anything more to do, let me know.

2025-08-20 20:19 UTC, merged

2025-08-20 20:19 UTC, jtheoof commented
Thanks !