Cleanup tmp files when exiting
jtheoof/swappy pull request #70
Opened 2020-12-06 19:18 UTC by apiraino

hey @jtheoof 

This PR ensure that swappy delete temp files when exiting

What do you think?

2020-12-24 10:16 UTC, apiraino commented
@jtheoof pinging for a review on this one (no rush, when you have time)

2021-01-08 21:27 UTC, jtheoof commented
I'm not sure to understand the need for this @apiraino. The variable serves to store the file name location and is freed using `g_free` when needed. Did you see a specific issue?

2021-01-08 21:51 UTC, apiraino commented
hi @jtheoof thanks for getting back.

yes, I do experience an issue: tmp files are not deleted in all cases (example: when the screenshot is not saved). If you can't reproduce I can recompile your upstream version and retry (but I'm quite sure I did so)

2021-02-13 18:37 UTC, apiraino commented
@jtheoof could you please check again this PR?

It fixes a minor (but annoying) papercut, temp files in `/tmp` are never deleted. I've tried solving this by manually calling a function to delete the temporary file the application is about to exit (with or without saving the file).

How to reproduce: run `grim -g "$(slurp)" - | swappy -f -`, select an area, then press <esc> key, now check `/tmp` for the temporary file for a leftover.

thanks

2021-02-13 20:15 UTC, jtheoof commented
Sorry about the late reply @apiraino I'm gonna try to reproduce this locally first. Will give you more feedback soon.

2021-02-13 21:04 UTC, jtheoof requested changes
This will delete existing files from the filesystem when not using the `stdin` shortcut.

I'll work a better fix.

2021-02-13 21:04 UTC, jtheoof commented on src/application.c
> +  if (g_unlink(state->file_str) != 0)
This works when using `-f -` command but will also delete a non temporary file when using:

```
./build/swappy -f docs/images/screenshot-1.0.0.png
```

I'm working on a better fix. Thanks for bringing this up @apiraino

2021-02-14 00:34 UTC, jtheoof commented
Thanks for bringing this up @apiraino. I merged #81 with a slightly better fix for the `-f` option. 

Can you try it out and let me know if you find issues?

2021-02-14 00:34 UTC, closed without merging

2021-02-16 09:51 UTC, apiraino commented
Sorry about my clumsy code fiddling :-) and thanks for providing the right fix