Added Void Linux package name to README
jtheoof/swappy pull request #72
Opened 2020-12-15 18:28 UTC by notramo

2020-12-15 19:09 UTC, jbeich commented
Why not always up-to-date badge instead?
[![Packaging status](https://repology.org/badge/vertical-allrepos/swappy.svg)](https://repology.org/project/swappy/versions)

2020-12-15 21:54 UTC, jtheoof commented
@jbeich would be happy to accept MR for that one. @notramo. The commint lint still does not pass. You see why in the logs.

2020-12-17 13:28 UTC, itspngu commented
Not meaning to hijack this discussion, but would you be willing to look into providing binary builds for some more distros @jtheoof? 

I could try and help with setting things up if that'd help, meant to look into Travis CI for a while anyway and got a vacation (+ covid lockdown) coming up ;)

2020-12-31 16:09 UTC, notramo commented
@jtheoof: The problem is that the commit message starts with capital letter. I can't force-push from the command line to my fork, and the web UI don't have an option to force-push.
Wouldn't it be easier if you added that simple line from your account?

2021-01-01 12:23 UTC, itspngu requested changes
> The problem is that the commit message starts with capital letter. I can't force-push from the command line to my fork, because GitHub doesn't allow it, and the web UI don't have an option to force-push.
Wouldn't it be easier if you added that simple line from your account?

I think it'd be easiest if you made a new branch, added a link to the void-sources repo tree as shown (so it's in line with the other distros), paid attention to formatting the commit message as needed by `commitlint`, and then submitted a new PR. My 2 cents. Cheers

2021-01-01 12:23 UTC, itspngu commented on README.md
> +- Void Linux: the `swappy` package
```suggestion
- [Void Linux](https://github.com/void-linux/void-packages/tree/master/srcpkgs/swappy)
```

2021-01-08 21:16 UTC, jtheoof commented
Thanks @itspngu @notramo. I've added the line in the README in [this commit](https://github.com/jtheoof/swappy/commit/a7fda1f998798811b54c8ee9dbfc147f43b97e96). I'll close this PR.

2021-01-08 21:16 UTC, closed without merging